import type { PricingPlan } from '../types';

export const plans: PricingPlan[] = [
  {
    name: "Basic",
    price: "$29",
    yearlyPrice: "$278",
    period: "/month",
    description: "Perfect for individual developers starting their AI journey",
    features: [
      { feature: "Access to basic AI Code Generator", included: true },
      { feature: "Basic Project Manager", included: true },
      { feature: "Up to 3 projects", included: true },
      { feature: "Basic version control integration", included: true },
      { feature: "Standard email support", included: true },
    ],
    buttonText: "Start Basic",
  },
  {
    name: "Pro",
    price: "$99",
    yearlyPrice: "$950",
    period: "/month",
    description: "Ideal for professional developers seeking advanced AI assistance",
    features: [
      { feature: "Full access to all AIDE features", included: true },
      { feature: "Unlimited projects", included: true },
      { feature: "Advanced CI/CD integration", included: true },
      { feature: "Priority support", included: true },
      { feature: "Access to learning materials", included: true },
    ],
    highlighted: true,
    buttonText: "Go Pro",
  },
  {
    name: "Academic",
    price: "$83",
    yearlyPrice: "$799",
    period: "/month",
    description: "Special offer for educational institutions",
    features: [
      { feature: "Access for students and faculty", included: true },
      { feature: "Specialized learning materials", included: true },
      { feature: "LMS integration", included: true },
      { feature: "Student progress tracking", included: true },
      { feature: "Academic support", included: true },
    ],
    buttonText: "Educate with AIDE",
  },
  {
    name: "Startup",
    price: "$499",
    yearlyPrice: "$4790",
    period: "/month",
    description: "Perfect for small teams up to 10 members",
    features: [
      { feature: "All Pro features", included: true },
      { feature: "Up to 10 users", included: true },
      { feature: "Collaboration tools", included: true },
      { feature: "Basic analytics and reporting", included: true },
      { feature: "Project management tool integrations", included: true },
    ],
    buttonText: "Empower Your Startup",
  },
  {
    name: "Business",
    price: "$1999",
    yearlyPrice: "$19190",
    period: "/month",
    description: "Tailored for growing businesses with up to 50 team members",
    features: [
      { feature: "All Startup features", included: true },
      { feature: "Up to 50 users", included: true },
      { feature: "Advanced analytics and reporting", included: true },
      { feature: "Custom AI model training", included: true },
      { feature: "API access for integrations", included: true },
    ],
    buttonText: "Scale Your Business",
  },
  {
    name: "Enterprise",
    price: "Custom",
    yearlyPrice: "Custom",
    period: "",
    description: "Fully customizable solution for large organizations",
    features: [
      { feature: "Unlimited users", included: true },
      { feature: "Full customization", included: true },
      { feature: "On-premise deployment option", included: true },
      { feature: "24/7 dedicated support", included: true },
      { feature: "Personalized AI models", included: true },
    ],
    buttonText: "Contact Sales",
  },
]; 